const portuguese = [
    "O destino favorece os corajosos. Não tema seguir em frente.",
    "Acredite em si mesmo, pois você é mais forte do que pensa.",
    "O amor verdadeiro nunca falha; permita-se amar e ser amado.",
    "Seja paciente; tudo acontece no momento certo.",
    "Cada desafio traz consigo uma oportunidade de crescimento.",
    "Confie em sua intuição; ela é sua bússola interna.",
    "Siga seu coração, mas leve sua mente junto.",
    "Mantenha o equilíbrio entre trabalho, descanso e lazer.",
    "Valorize as pequenas coisas; elas têm um grande significado.",
    "A gratidão é a chave para uma vida plena; seja grato pelo que você tem.",
    "Cuide do seu corpo, mente e espírito; são os seus maiores tesouros.",
    "Não se preocupe com o que os outros pensam de você; seja autêntico.",
    "A vida é uma jornada; desfrute do caminho, não apenas do destino.",
    "Perdoe aqueles que te machucaram; o perdão traz libertação.",
    "Seja gentil com os outros, você nunca sabe que batalhas eles estão enfrentando.",
    "A adversidade é apenas um teste; você é mais forte do que imagina.",
    "Abra-se para novas experiências; elas podem trazer surpresas maravilhosas.",
    "Não se prenda ao passado; o presente é onde a magia acontece.",
    "A vida é feita de altos e baixos; abrace todas as suas emoções.",
    "Aprenda com seus erros; eles são oportunidades de crescimento.",
    "Não compare sua jornada com a dos outros; cada um tem seu próprio caminho.",
    "Seja paciente com você mesmo; o progresso leva tempo.",
    "A verdadeira beleza vem de dentro; cultive sua essência.",
    "Aprenda a dizer não quando necessário; seu tempo e energia são preciosos.",
    "O universo conspira a seu favor; confie no processo.",
    "Não se apegue ao material; as verdadeiras riquezas estão nas relações e experiências.",
    "O amor-próprio é a base de todas as outras formas de amor.",
    "A simplicidade é a chave para a felicidade; valorize o que realmente importa.",
    "Mantenha-se fiel aos seus valores; eles são sua bússola moral.",
    "Não tema a mudança; ela é inevitável e necessária para o crescimento.",
    "Aceite os desafios como oportunidades de aprendizado.",
    "Encontre alegria nas coisas simples da vida; elas são as mais preciosas.",
    "Seja flexível como o bambu; dobre, mas nunca quebre.",
    "A autenticidade é sua maior força; seja verdadeiro consigo mesmo.",
    "Não se preocupe com o que não pode controlar; concentre-se no que pode.",
    "Acredite no poder dos seus sonhos; eles têm o potencial de se tornarem realidade.",
    "Expresse sua gratidão diariamente; ela atrai mais motivos para ser grato.",
    "Aprenda a se desapegar do que não serve mais; isso abrirá espaço para o novo.",
    "Seja paciente com os outros; todos estão em sua própria jornada de crescimento.",
    "A vida é um presente; viva cada momento com gratidão e alegria.",
    "Aprecie a beleza ao seu redor; ela está presente nos detalhes mais simples.",
    "Nunca subestime o poder da gentileza; ela pode transformar vidas.",
    "Abrace a incerteza; é nela que reside a magia da vida.",
    "Não se preocupe com o futuro; foque no presente e faça o seu melhor agora.",
    "Seja um farol de luz para os outros; seu brilho pode iluminar o caminho.",
    "Valorize seus relacionamentos; são eles que tornam a jornada da vida significativa.",
    "Aprenda a ouvir sua voz interior; ela sempre sabe o melhor para você.",
    "Não tenha medo de falhar; é através dos fracassos que você aprende e cresce.",
    "Mantenha uma mente aberta; o conhecimento e a sabedoria estão em constante evolução.",
    "Não se compare aos outros; você é único e tem seu próprio caminho a seguir.",
    "Pratique a autocompaixão; seja gentil consigo mesmo em tempos de dificuldade.",
    "Siga seus sonhos com coragem e determinação; o universo está torcendo por você.",
    "Aprecie os momentos de tranquilidade; é neles que você encontra clareza e paz.",
    "Não se deixe levar pelo medo; ele é apenas uma ilusão que limita seu potencial.",
    "Seja grato pelas lições que a vida lhe oferece; elas são oportunidades de crescimento.",
    "Encontre alegria na jornada, não apenas no destino final.",
    "A vida é uma dança; siga o ritmo do universo e deixe-se levar pela música da existência.",
    "Cultive a paciência; grandes coisas levam tempo para se manifestar.",
    "Esteja presente em cada momento; é neles que a magia da vida acontece.",
    "Confie no poder do universo; ele sempre guiará você na direção certa.",
    "Não tema a escuridão; é nela que você descobre a sua própria luz.",
    "Seja gentil com você mesmo; você é seu melhor amigo e aliado.",
    "A vida é um presente precioso; viva-a com gratidão e alegria.",
    "Siga os sinais do universo; eles são pistas para o seu destino.",
    "Não se preocupe com o que os outros pensam de você; siga o seu próprio caminho com confiança.",
    "Aceite o que você não pode mudar; concentre-se no que está ao seu alcance.",
    "Encontre beleza na imperfeição; é ela que torna a vida interessante e única.",
    "Mantenha a fé, mesmo nos momentos mais sombrios; a luz sempre prevalecerá.",
    "Compartilhe seu amor e bondade com o mundo; é isso que faz a diferença.",
    "Não se esqueça de cuidar de si mesmo; sua saúde e bem-estar são prioridades.",
    "Aprenda a dizer sim para novas oportunidades; elas podem levá-lo a lugares inesperados.",
    "Seja grato pelas pessoas em sua vida; elas são presentes preciosos.",
    "Não se preocupe com o que poderia dar errado; concentre-se no que pode dar certo.",
    "Confie em sua jornada; cada desafio é uma oportunidade de crescimento.",
    "Seja corajoso em suas escolhas; é assim que você descobre o que é possível.",
    "Não se esqueça de celebrar suas vitórias; elas são um testemunho do seu poder.",
    "Aprenda a deixar ir o que não serve mais; é aí que reside sua liberdade.",
    "Valorize a jornada tanto quanto o destino; é onde você encontra sua verdadeira essência.",
    "Aprenda a se amar incondicionalmente; é aí que reside seu poder.",
    "Não se preocupe com o que você não pode controlar; concentre-se no que você pode fazer.",
    "Encontre alegria nas coisas simples da vida; elas são o que torna a vida verdadeiramente bela.",
    "Seja gentil com os outros, mesmo quando você discorda; é aí que reside a verdadeira grandeza.",
    "Confie em sua intuição; ela é sua bússola interior, guiando-o na direção certa.",
    "Aprenda a viver com gratidão; é aí que reside a verdadeira riqueza da vida.",
    "Seja paciente com os outros; todos estão lutando suas próprias batalhas.",
    "Não se preocupe com o futuro; concentre-se no presente e no que está ao seu alcance.",
    "Acredite no poder dos seus sonhos; eles têm o poder de moldar o seu destino.",
    "Seja gentil consigo mesmo; você é seu melhor amigo e aliado nesta jornada da vida.",
    "Não se esqueça de rir e se divertir; é aí que reside a verdadeira magia da vida."
]

module.exports = portuguese