const french = [
    "Le destin favorise les audacieux. N'ayez pas peur d'avancer.",
    "Croyez en vous-même, car vous êtes plus fort que vous ne le pensez.",
    "Le véritable amour ne déçoit jamais ; autorisez-vous à aimer et à être aimé.",
    "Soyez patient ; tout arrive en son temps.",
    "Chaque défi apporte avec lui une opportunité de croissance.",
    "Faites confiance à votre intuition ; c'est votre boussole intérieure.",
    "Suivez votre cœur, mais emportez votre esprit avec vous.",
    "Maintenez l'équilibre entre le travail, le repos et les loisirs.",
    "Valorisez les petites choses ; elles ont une grande signification.",
    "La gratitude est la clé d'une vie épanouie ; soyez reconnaissant pour ce que vous avez.",
    "Prenez soin de votre corps, de votre esprit et de votre esprit ; ce sont vos plus grands trésors.",
    "Ne vous souciez pas de ce que les autres pensent de vous ; soyez authentique.",
    "La vie est un voyage ; appréciez le chemin, pas seulement la destination.",
    "Pardonnez à ceux qui vous ont blessé ; le pardon apporte la libération.",
    "Soyez gentil avec les autres ; vous ne savez jamais quels combats ils affrontent.",
    "L'adversité n'est qu'un test ; vous êtes plus fort que vous ne l'imaginez.",
    "Ouvrez-vous à de nouvelles expériences ; elles peuvent apporter de merveilleuses surprises.",
    "Ne vous attardez pas sur le passé ; le présent est là où la magie se produit.",
    "La vie est faite de hauts et de bas ; embrassez toutes vos émotions.",
    "Apprenez de vos erreurs ; ce sont des opportunités de croissance.",
    "Ne comparez pas votre parcours à celui des autres ; chacun a son propre chemin.",
    "Soyez patient avec vous-même ; le progrès prend du temps.",
    "La vraie beauté vient de l'intérieur ; cultivez votre essence.",
    "La simplicité est la clé du bonheur ; valorisez ce qui compte vraiment.",
    "Restez fidèle à vos valeurs ; elles sont votre boussole morale.",
    "Ne craignez pas le changement ; il est inévitable et nécessaire pour grandir.",
    "Acceptez les défis comme des opportunités d'apprentissage.",
    "Trouvez la joie dans les petites choses de la vie ; elles sont les plus précieuses.",
    "Soyez aussi flexible que le bambou ; pliez-vous, mais ne cassez jamais.",
    "L'authenticité est votre plus grande force ; soyez fidèle à vous-même.",
    "Ne vous inquiétez pas de ce que vous ne pouvez pas contrôler ; concentrez-vous sur ce que vous pouvez.",
    "Croyez en le pouvoir de vos rêves ; ils ont le potentiel de devenir réalité.",
    "Exprimez votre gratitude quotidiennement ; elle attire plus de raisons d'être reconnaissant.",
    "Apprenez à lâcher prise de ce qui ne vous sert plus ; cela fera place au nouveau.",
    "Soyez patient avec les autres ; chacun est sur son propre chemin de croissance.",
    "La vie est un précieux cadeau ; vivez chaque moment avec gratitude et joie.",
    "Appréciez la beauté qui vous entoure ; elle est présente dans les moindres détails.",
    "Sous-estimez jamais le pouvoir de la gentillesse ; elle peut transformer des vies.",
    "Acceptez l'incertitude ; c'est là que réside la magie de la vie.",
    "Ne vous inquiétez pas de l'avenir ; concentrez-vous sur le présent et faites de votre mieux maintenant.",
    "Soyez un phare pour les autres ; votre éclat peut illuminer le chemin.",
    "Valorisez vos relations ; elles donnent un sens au voyage de la vie.",
    "Apprenez à écouter votre voix intérieure ; elle sait toujours ce qui est le mieux pour vous.",
    "N'ayez pas peur d'échouer ; c'est à travers les échecs que vous apprenez et grandissez.",
    "Gardez l'esprit ouvert ; la connaissance et la sagesse évoluent constamment.",
    "Ne vous comparez pas aux autres ; vous êtes unique et avez votre propre chemin à suivre.",
    "Pratiquez la compassion envers vous-même ; soyez gentil avec vous-même en période de difficulté.",
    "Suivez vos rêves avec courage et détermination ; l'univers est de votre côté.",
    "Trouvez la joie dans les moments de calme ; c'est là que vous trouvez clarté et paix.",
    "Ne vous laissez pas influencer par la peur ; c'est simplement une illusion qui limite votre potentiel.",
    "Soyez reconnaissant pour les leçons que la vie vous offre ; ce sont des occasions de croissance.",
    "Trouvez la joie dans le voyage, pas seulement la destination.",
    "La vie est une danse ; suivez le rythme de l'univers et laissez-vous porter par la musique de l'existence.",
    "Cultivez la patience ; les grandes choses prennent du temps à se manifester.",
    "Soyez présent dans chaque moment ; c'est là que la magie de la vie se produit.",
    "Faites confiance au pouvoir de l'univers ; il vous guidera toujours dans la bonne direction.",
    "Ne craignez pas l'obscurité ; c'est là que vous découvrez votre propre lumière.",
    "Soyez gentil avec vous-même ; vous êtes votre meilleur ami et allié.",
    "La vie est un précieux cadeau ; vivez-la avec gratitude et joie.",
    "Suivez les signes de l'univers ; ce sont des indices sur votre destin.",
    "Ne vous inquiétez pas de ce que les autres pensent de vous ; suivez votre propre chemin avec confiance.",
    "Acceptez ce que vous ne pouvez pas changer ; concentrez-vous sur ce qui est à votre portée.",
    "Trouvez la beauté dans l'imperfection ; c'est ce qui rend la vie intéressante et unique.",
    "Gardez la foi, même dans les moments les plus sombres ; la lumière prévaudra toujours.",
    "Partagez votre amour et votre gentillesse avec le monde ; voilà où réside le véritable bonheur.",
    "Soyez reconnaissant pour chaque nouvelle journée ; c'est une chance de recommencer.",
    "Soyez un phare pour les autres ; votre lumière peut guider ceux qui sont perdus.",
    "Ne laissez pas la peur vous retenir ; laissez-la être votre moteur pour la croissance.",
    "Lâchez prise de ce qui ne vous sert plus ; cela vous libérera pour de nouvelles possibilités.",
    "Chaque défi est une occasion de grandir ; ne le craignez pas, mais apprenez de lui.",
    "Soyez doux avec vous-même ; vous êtes en train de grandir et d'apprendre.",
    "Trouvez la joie dans les petites victoires de la vie ; elles sont toutes précieuses.",
    "Soyez ouvert à l'inconnu ; c'est là que se trouvent les plus grandes opportunités.",
    "Croyez en votre pouvoir de créer la vie que vous désirez ; vous êtes plus puissant que vous ne le pensez.",
    "Faites confiance au processus de la vie ; tout se déroule exactement comme il le devrait.",
    "Appréciez le voyage autant que la destination ; chaque étape a sa propre beauté.",
    "Soyez un exemple de bonté et de compassion ; le monde a besoin de plus de lumière.",
    "Croyez en vous-même, même lorsque personne d'autre ne le fait ; vous êtes votre propre meilleur allié.",
    "Soyez patient avec les autres ; tout le monde est en train de grandir à son propre rythme.",
    "Ne laissez pas la peur vous empêcher d'essayer ; c'est là que se trouvent les plus grandes réalisations.",
    "Soyez reconnaissant pour chaque expérience de vie ; elles ont toutes quelque chose à vous enseigner.",
    "Chaque jour est une nouvelle chance de devenir la meilleure version de vous-même ; saisissez-la avec gratitude.",
    "Faites confiance à votre intuition ; elle est rarement fausse.",
    "Soyez ouvert à la possibilité de miracles ; ils se produisent plus souvent que vous ne le pensez.",
    "N'oubliez pas de prendre du temps pour vous-même ; votre bien-être est important.",
    "Apprenez à être à l'aise avec l'inconnu ; c'est là que la magie se produit.",
    "Soyez ouvert à la possibilité de changement ; c'est là que réside la croissance.",
    "Chaque expérience de vie est une leçon ; soyez attentif à ce qu'elle a à vous enseigner.",
    "Soyez reconnaissant pour chaque nouvelle journée ; elle est une opportunité de recommencer.",
    "Faites preuve de gratitude pour les leçons apprises et les défis surmontés ; ils vous rendent plus fort.",
    "Ne laissez pas la peur vous retenir ; avancez avec courage et détermination.",
    "Cultivez un esprit de gratitude ; cela vous apportera plus de bonheur et de paix intérieure.",
    "Soyez ouvert à l'impermanence de la vie ; c'est là que réside sa beauté et sa magie.",
    "Faites confiance à votre voyage ; même les détours ont leur propre signification.",
    "Ne laissez pas la peur vous empêcher de suivre vos rêves ; osez vous aventurer dans l'inconnu.",
    "Apprenez à lâcher prise de ce qui ne vous sert plus ; cela vous ouvrira la voie à de nouvelles possibilités.",
    "Soyez ouvert à la possibilité de changement ; c'est là que réside la croissance personnelle.",
    "Soyez gentil avec vous-même ; vous faites de votre mieux et c'est tout ce qui compte.",
    "Chaque jour est une nouvelle opportunité de grandir et d'apprendre ; saisissez-la avec gratitude.",
    "Faites preuve de compassion envers vous-même ; vous méritez d'être aimé et apprécié.",
    "Ne vous attardez pas sur le passé ; concentrez-vous sur le présent et sur ce qui est à venir.",
    "Soyez reconnaissant pour les petites choses de la vie ; elles sont souvent les plus importantes.",
    "Ne laissez pas la peur vous retenir ; osez sortir de votre zone de confort et explorer de nouvelles possibilités.",
    "Soyez ouvert à la possibilité de miracles ; ils se produisent souvent lorsque vous y moins vous attendez.",
    "Faites preuve de patience dans toutes les choses ; chaque chose vient en son temps.",
    "Croyez en votre pouvoir de changer votre vie ; vous êtes le seul à pouvoir réaliser vos rêves.",
    "Soyez reconnaissant pour les leçons que la vie vous offre ; elles vous aident à grandir et à évoluer.",
    "Chaque défi est une opportunité de croissance ; ne le craignez pas, mais embrassez-le.",
    "Apprenez à écouter votre intuition ; elle est souvent plus sage que votre esprit.",
    "Soyez ouvert aux possibilités infinies de l'univers ; elles sont plus grandes que vous ne pouvez l'imaginer.",
    "Soyez reconnaissant pour chaque nouvelle journée ; c'est une chance de recommencer.",
    "N'ayez pas peur de l'échec ; c'est une occasion d'apprendre et de grandir.",
    "Faites preuve de gentillesse envers vous-même et envers les autres ; elle est la clé de la connexion humaine.",
    "Croyez en votre propre capacité à créer la vie que vous désirez ; vous avez le pouvoir de le réaliser.",
    "Soyez ouvert à la possibilité de miracles ; ils peuvent survenir lorsque vous y moins vous attendez.",
    "Apprenez à lâcher prise de ce qui ne vous sert plus ; cela vous permettra de vous ouvrir à de nouvelles possibilités.",
    "Soyez patient avec les autres ; tout le monde est en train de grandir et d'apprendre à son propre rythme.",
    "Ne laissez pas la peur vous empêcher de poursuivre vos rêves ; osez vous aventurer dans l'inconnu.",
    "Exprimez votre gratitude quotidiennement ; cela ouvrira votre cœur à plus d'amour et de compassion.",
    "Soyez présent dans chaque moment ; c'est là que réside la plénitude et la joie de vivre.",
    "Croyez en votre propre capacité à surmonter les défis ; vous êtes plus fort que vous ne le pensez.",
    "Ne sous-estimez jamais le pouvoir de la gentillesse ; elle peut guérir les cœurs et changer des vies.",
    "Apprenez à lâcher prise de ce qui ne vous sert plus ; cela vous libérera pour de nouveaux départs.",
    "Soyez reconnaissant pour chaque expérience de vie ; elles ont toutes quelque chose à vous enseigner.",
    "Chaque défi est une occasion de croissance ; ne le craignez pas, mais embrassez-le.",
    "Soyez doux avec vous-même ; vous êtes en train de grandir et d'apprendre.",
    "Trouvez la joie dans les petites victoires de la vie ; elles sont toutes précieuses.",
    "Soyez ouvert à l'inconnu ; c'est là que se trouvent les plus grandes opportunités.",
    "Croyez en votre pouvoir de créer la vie que vous désirez ; vous êtes plus puissant que vous ne le pensez.",
    "Faites confiance au processus de la vie ; tout se déroule exactement comme il le devrait.",
    "Appréciez le voyage autant que la destination ; chaque étape a sa propre beauté.",
    "Soyez un exemple de bonté et de compassion ; le monde a besoin de plus de lumière.",
    "Croyez en vous-même, même lorsque personne d'autre ne le fait ; vous êtes votre propre meilleur allié.",
    "Soyez patient avec les autres ; tout le monde est en train de grandir à son propre rythme.",
    "Ne laissez pas la peur vous empêcher d'essayer ; c'est là que se trouvent les plus grandes réalisations.",
    "Soyez reconnaissant pour chaque expérience de vie ; elles ont toutes quelque chose à vous enseigner.",
    "Chaque jour est une nouvelle chance de devenir la meilleure version de vous-même ; saisissez-la avec gratitude.",
    "Faites preuve de gratitude pour les leçons apprises et les défis surmontés ; ils vous rendent plus fort.",
    "Ne laissez pas la peur vous retenir ; avancez avec courage et détermination.",
    "Cultivez un esprit de gratitude ; cela vous apportera plus de bonheur et de paix intérieure.",
    "Soyez ouvert à l'impermanence de la vie ; c'est là que réside sa beauté et sa magie.",
    "Faites confiance à votre voyage ; même les détours ont leur propre signification.",
    "Ne laissez pas la peur vous empêcher de suivre vos rêves ; osez vous aventurer dans l'inconnu.",
    "Apprenez à lâcher prise de ce qui ne vous sert plus ; cela vous ouvrira la voie à de nouvelles possibilités.",
    "Soyez ouvert à la possibilité de changement ; c'est là que réside la croissance personnelle.",
    "Soyez gentil avec vous-même ; vous faites de votre mieux et c'est tout ce qui compte.",
    "Chaque jour est une nouvelle opportunité de grandir et d'apprendre ; saisissez-la avec gratitude.",
    "Faites preuve de compassion envers vous-même ; vous méritez d'être aimé et apprécié.",
    "Ne vous attardez pas sur le passé ; concentrez-vous sur le présent et sur ce qui est à venir.",
    "Soyez reconnaissant pour les petites choses de la vie ; elles sont souvent les plus importantes.",
    "Ne laissez pas la peur vous retenir ; osez sortir de votre zone de confort et explorer de nouvelles possibilités.",
    "Soyez ouvert à la possibilité de miracles ; ils se produisent souvent lorsque vous y moins vous attendez.",
    "Faites preuve de patience dans toutes les choses ; chaque chose vient en son temps.",
    "Croyez en votre pouvoir de changer votre vie ; vous êtes le seul à pouvoir réaliser vos rêves.",
    "Soyez reconnaissant pour les leçons que la vie vous offre ; elles vous aident à grandir et à évoluer.",
    "Chaque défi est une opportunité de croissance ; ne le craignez pas, mais embrassez-le.",
    "Apprenez à écouter votre intuition ; elle est souvent plus sage que votre esprit.",
    "Soyez ouvert aux possibilités infinies de l'univers ; elles sont plus grandes que vous ne pouvez l'imaginer.",
    "Soyez reconnaissant pour chaque nouvelle journée ; c'est une chance de recommencer.",
    "N'ayez pas peur de l'échec ; c'est une occasion d'apprendre et de grandir.",
    "Faites preuve de gentillesse envers vous-même et envers les autres ; elle est la clé de la connexion humaine.",
    "Croyez en votre propre capacité à créer la vie que vous désirez ; vous avez le pouvoir de le réaliser.",
    "Soyez ouvert à la possibilité de miracles ; ils peuvent survenir lorsque vous y moins vous attendez.",
    "Apprenez à lâcher prise de ce qui ne vous sert plus ; cela vous permettra de vous ouvrir à de nouvelles possibilités.",
    "Soyez patient avec les autres ; tout le monde est en train de grandir et d'apprendre à son propre rythme.",
    "Ne laissez pas la peur vous empêcher de poursuivre vos rêves ; osez vous aventurer dans l'inconnu.",
    "Exprimez votre gratitude quotidiennement ; cela ouvrira votre cœur à plus d'amour et de compassion.",
    "Soyez présent dans chaque moment ; c'est là que réside la plénitude et la joie de vivre.",
    "Croyez en votre propre capacité à surmonter les défis ; vous êtes plus fort que vous ne le pensez.",
    "Ne sous-estimez jamais le pouvoir de la gentillesse ; elle peut guérir les cœurs et changer des vies.",
    "Apprenez à lâcher prise de ce qui ne vous sert plus ; cela vous ouvrira la voie à de nouveaux départs.",
    "Soyez reconnaissant pour chaque expérience de vie ; elles ont toutes quelque chose à vous enseigner.",
    "Chaque défi est une occasion de croissance ; ne le craignez pas, mais embrassez-le.",
    "Soyez doux avec vous-même ; vous êtes en train de grandir et d'apprendre.",
    "Trouvez la joie dans les petites victoires de la vie ; elles sont toutes précieuses.",
    "Soyez ouvert à l'inconnu ; c'est là que se trouvent les plus grandes opportunités.",
    "Croyez en votre pouvoir de créer la vie que vous désirez ; vous êtes plus puissant que vous ne le pensez.",
    "Faites confiance au processus de la vie ; tout se déroule exactement comme il le devrait.",
    "Appréciez le voyage autant que la destination ; chaque étape a sa propre beauté.",
    "Soyez un exemple de bonté et de compassion ; le monde a besoin de plus de lumière.",
    "Croyez en vous-même, même lorsque personne d'autre ne le fait ; vous êtes votre propre meilleur allié.",
    "Soyez patient avec les autres ; tout le monde est en train de grandir à son propre rythme.",
    "Ne laissez pas la peur vous empêcher d'essayer ; c'est là que se trouvent les plus grandes réalisations.",
    "Soyez reconnaissant pour chaque expérience de vie ; elles ont toutes quelque chose à vous enseigner.",
    "Chaque jour est une nouvelle chance de devenir la meilleure version de vous-même ; saisissez-la avec gratitude.",
    "Faites preuve de gratitude pour les leçons apprises et les défis surmontés ; ils vous rendent plus fort.",
    "Ne laissez pas la peur vous retenir ; avancez avec courage et détermination.",
    "Cultivez un esprit de gratitude ; cela vous apportera plus de bonheur et de paix intérieure.",
    "Soyez ouvert à l'impermanence de la vie ; c'est là que réside sa beauté et sa magie.",
    "Faites confiance à votre voyage ; même les détours ont leur propre signification.",
    "Ne laissez pas la peur vous empêcher de suivre vos rêves ; osez vous aventurer dans l'inconnu.",
    "Apprenez à lâcher prise de ce qui ne vous sert plus ; cela vous ouvrira la voie à de nouvelles possibilités.",
    "Soyez ouvert à la possibilité de changement ; c'est là que réside la croissance personnelle.",
    "Soyez gentil avec vous-même ; vous faites de votre mieux et c'est tout ce qui compte.",
    "Chaque jour est une nouvelle opportunité de grandir et d'apprendre ; saisissez-la avec gratitude.",
    "Faites preuve de compassion envers vous-même ; vous méritez d'être aimé et apprécié.",
    "Ne vous attardez pas sur le passé ; concentrez-vous sur le présent et sur ce qui est à venir.",
    "Soyez reconnaissant pour les petites choses de la vie ; elles sont souvent les plus importantes.",
    "Ne laissez pas la peur vous retenir ; osez sortir de votre zone de confort et explorer de nouvelles possibilités.",
    "Soyez ouvert à la possibilité de miracles ; ils se produisent souvent lorsque vous y moins vous attendez.",
    "Faites preuve de patience dans toutes les choses ; chaque chose vient en son temps.",
    "Croyez en votre pouvoir de changer votre vie ; vous êtes le seul à pouvoir réaliser vos rêves.",
    "Soyez reconnaissant pour les leçons que la vie vous offre ; elles vous aident à grandir et à évoluer.",
    "Chaque défi est une opportunité de croissance ; ne le craignez pas, mais embrassez-le.",
    "Apprenez à écouter votre intuition ; elle est souvent plus sage que votre esprit.",
    "Soyez ouvert aux possibilités infinies de l'univers ; elles sont plus grandes que vous ne pouvez l'imaginer.",
    "Soyez reconnaissant pour chaque nouvelle journée ; c'est une chance de recommencer.",
    "N'ayez pas peur de l'échec ; c'est une occasion d'apprendre et de grandir.",
    "Faites preuve de gentillesse envers vous-même et envers les autres ; elle est la clé de la connexion humaine.",
    "Croyez en votre propre capacité à créer la vie que vous désirez ; vous avez le pouvoir de le réaliser.",
    "Soyez ouvert à la possibilité de miracles ; ils peuvent survenir lorsque vous y moins vous attendez.",
    "Apprenez à lâcher prise de ce qui ne vous sert plus ; cela vous permettra de vous ouvrir à de nouvelles possibilités.",
    "Soyez patient avec les autres ; tout le monde est en train de grandir et d'apprendre à son propre rythme.",
    "Ne laissez pas la peur vous empêcher de poursuivre vos rêves ; osez vous aventurer dans l'inconnu.",
    "Exprimez votre gratitude quotidiennement ; cela ouvrira votre cœur à plus d'amour et de compassion.",
    "Soyez présent dans chaque moment ; c'est là que réside la plénitude et la joie de vivre.",
    "Croyez en votre propre capacité à surmonter les défis ; vous êtes plus fort que vous ne le pensez.",
    "Ne sous-estimez jamais le pouvoir de la gentillesse ; elle peut guérir les cœurs et changer des vies.",
    "Apprenez à lâcher prise de ce qui ne vous sert plus ; cela vous ouvrira la voie à de nouveaux départs.",
    "Soyez reconnaissant pour chaque expérience de vie ; elles ont toutes quelque chose à vous enseigner.",
    "Chaque défi est une occasion de croissance ; ne le craignez pas, mais embrassez-le.",
    "Soyez doux avec vous-même ; vous êtes en train de grandir et d'apprendre.",
    "Trouvez la joie dans les petites victoires de la vie ; elles sont toutes précieuses.",
    "Soyez ouvert à l'inconnu ; c'est là que se trouvent les plus grandes opportunités.",
    "Croyez en votre pouvoir de créer la vie que vous désirez ; vous êtes plus puissant que vous ne le pensez.",
    "Faites confiance au processus de la vie ; tout se déroule exactement comme il le devrait.",
    "Appréciez le voyage autant que la destination ; chaque étape a sa propre beauté.",
    "Soyez un exemple de bonté et de compassion ; le monde a besoin de plus de lumière.",
    "Croyez en vous-même, même lorsque personne d'autre ne le fait ; vous êtes votre propre meilleur allié.",
    "Soyez patient avec les autres ; tout le monde est en train de grandir à son propre rythme.",
    "Ne laissez pas la peur vous empêcher d'essayer ; c'est là que se trouvent les plus grandes réalisations.",
    "Soyez reconnaissant pour chaque expérience de vie ; elles ont toutes quelque chose à vous enseigner.",
    "Chaque jour est une nouvelle chance de devenir la meilleure version de vous-même ; saisissez-la avec gratitude.",
    "Faites preuve de gratitude pour les leçons apprises et les défis surmontés ; ils vous rendent plus fort.",
    "Ne laissez pas la peur vous retenir ; avancez avec courage et détermination.",
    "Cultivez un esprit de gratitude ; cela vous apportera plus de bonheur et de paix intérieure.",
    "Soyez ouvert à l'impermanence de la vie ; c'est là que réside sa beauté et sa magie.",
    "Faites confiance à votre voyage ; même les détours ont leur propre signification.",
    "Ne laissez pas la peur vous empêcher de suivre vos rêves ; osez vous aventurer dans l'inconnu.",
    "Apprenez à lâcher prise de ce qui ne vous sert plus ; cela vous ouvrira la voie à de nouvelles possibilités.",
    "Soyez ouvert à la possibilité de changement ; c'est là que réside la croissance personnelle.",
    "Soyez gentil avec vous-même ; vous faites de votre mieux et c'est tout ce qui compte.",
    "Chaque jour est une nouvelle opportunité de grandir et d'apprendre ; saisissez-la avec gratitude.",
    "Faites preuve de compassion envers vous-même ; vous méritez d'être aimé et apprécié.",
    "Ne vous attardez pas sur le passé ; concentrez-vous sur le présent et sur ce qui est à venir.",
    "Soyez reconnaissant pour les petites choses de la vie ; elles sont souvent les plus importantes.",
    "Ne laissez pas la peur vous retenir ; osez sortir de votre zone de confort et explorer de nouvelles possibilités.",
    "Soyez ouvert à la possibilité de miracles ; ils se produisent souvent lorsque vous y moins vous attendez.",
    "Faites preuve de patience dans toutes les choses ; chaque chose vient en son temps.",
    "Croyez en votre pouvoir de changer votre vie ; vous êtes le seul à pouvoir réaliser vos rêves.",
    "Soyez reconnaissant pour les leçons que la vie vous offre ; elles vous aident à grandir et à évoluer.",
    "Chaque défi est une opportunité de croissance ; ne le craignez pas, mais embrassez-le.",
    "Apprenez à écouter votre intuition ; elle est souvent plus sage que votre esprit.",
    "Soyez ouvert aux possibilités infinies de l'univers ; elles sont plus grandes que vous ne pouvez l'imaginer.",
    "Soyez reconnaissant pour chaque nouvelle journée ; c'est une chance de recommencer.",
    "N'ayez pas peur de l'échec ; c'est une occasion d'apprendre et de grandir.",
    "Faites preuve de gentillesse envers vous-même et envers les autres ; elle est la clé de la connexion humaine.",
    "Croyez en votre propre capacité à créer la vie que vous désirez ; vous avez le pouvoir de le réaliser.",
    "Soyez ouvert à la possibilité de miracles ; ils peuvent survenir lorsque vous y moins vous attendez.",
    "Apprenez à lâcher prise de ce qui ne vous sert plus ; cela vous permettra de vous ouvrir à de nouvelles possibilités.",
    "Soyez patient avec les autres ; tout le monde est en train de grandir et d'apprendre à son propre rythme.",
    "Ne laissez pas la peur vous empêcher de poursuivre vos rêves ; osez vous aventurer dans l'inconnu.",
    "Exprimez votre gratitude quotidiennement ; cela ouvrira votre cœur à plus d'amour et de compassion.",
    "Soyez présent dans chaque moment ; c'est là que réside la plénitude et la joie de vivre.",
    "Croyez en votre propre capacité à surmonter les défis ; vous êtes plus fort que vous ne le pensez.",
    "Ne sous-estimez jamais le pouvoir de la gentillesse ; elle peut guérir les cœurs et changer des vies.",
    "Apprenez à lâcher prise de ce qui ne vous sert plus ; cela vous ouvrira la voie à de nouveaux départs.",
    "Soyez reconnaissant pour chaque expérience de vie ; elles ont toutes quelque chose à vous enseigner.",
    "Chaque défi est une occasion de croissance ; ne le craignez pas, mais embrassez-le.",
    "Soyez doux avec vous-même ; vous êtes en train de grandir et d'apprendre.",
    "Trouvez la joie dans les petites victoires de la vie ; elles sont toutes précieuses.",
    "Soyez ouvert à l'inconnu ; c'est là que se trouvent les plus grandes opportunités.",
    "Croyez en votre pouvoir de créer la vie que vous désirez ; vous êtes plus puissant que vous ne le pensez.",
    "Faites confiance au processus de la vie ; tout se déroule exactement comme il le devrait.",
    "Appréciez le voyage autant que la destination ; chaque étape a sa propre beauté.",
    "Soyez un exemple de bonté et de compassion ; le monde a besoin de plus de lumière.",
    "Croyez en vous-même, même lorsque personne d'autre ne le fait ; vous êtes votre propre meilleur allié.",
    "Soyez patient avec les autres ; tout le monde est en train de grandir à son propre rythme.",
    "Ne laissez pas la peur vous empêcher d'essayer ; c'est là que se trouvent les plus grandes réalisations.",
    "Soyez reconnaissant pour chaque expérience de vie ; elles ont toutes quelque chose à vous enseigner.",
    "Chaque jour est une nouvelle chance de devenir la meilleure version de vous-même ; saisissez-la avec gratitude.",
    "Faites preuve de gratitude pour les leçons apprises et les défis surmontés ; ils vous rendent plus fort.",
    "Ne laissez pas la peur vous retenir ; avancez avec courage et détermination.",
    "Cultivez un esprit de gratitude ; cela vous apportera plus de bonheur et de paix intérieure.",
    "Soyez ouvert à l'impermanence de la vie ; c'est là que réside sa beauté et sa magie.",
    "Faites confiance à votre voyage ; même les détours ont leur propre signification.",
    "Ne laissez pas la peur vous empêcher de suivre vos rêves ; osez vous aventurer dans l'inconnu.",
    "Apprenez à lâcher prise de ce qui ne vous sert plus ; cela vous ouvrira la voie à de nouvelles possibilités.",
    "Soyez ouvert à la possibilité de changement ; c'est là que réside la croissance personnelle.",
    "Soyez gentil avec vous-même ; vous faites de votre mieux et c'est tout ce qui compte.",
    "Chaque jour est une nouvelle opportunité de grandir et d'apprendre ; saisissez-la avec gratitude.",
    "Faites preuve de compassion envers vous-même ; vous méritez d'être aimé et apprécié.",
    "Ne vous attardez pas sur le passé ; concentrez-vous sur le présent et sur ce qui est à venir.",
    "Soyez reconnaissant pour les petites choses de la vie ; elles sont souvent les plus importantes.",
    "Ne laissez pas la peur vous retenir ; osez sortir de votre zone de confort et explorer de nouvelles possibilités.",
    "Soyez ouvert à la possibilité de miracles ; ils se produisent souvent lorsque vous y moins vous attendez.",
    "Faites preuve de patience dans toutes les choses ; chaque chose vient en son temps.",
    "Croyez en votre pouvoir de changer votre vie ; vous êtes le seul à pouvoir réaliser vos rêves.",
    "Soyez reconnaissant pour les leçons que la vie vous offre ; elles vous aident à grandir et à évoluer.",
    "Chaque défi est une opportunité de croissance ; ne le craignez pas, mais embrassez-le.",
    "Apprenez à écouter votre intuition ; elle est souvent plus sage que votre esprit.",
    "Soyez ouvert aux possibilités infinies de l'univers ; elles sont plus grandes que vous ne pouvez l'imaginer.",
    "Soyez reconnaissant pour chaque nouvelle journée ; c'est une chance de recommencer.",
    "N'ayez pas peur de l'échec ; c'est une occasion d'apprendre et de grandir.",
    "Faites preuve de gentillesse envers vous-même et envers les autres ; elle est la clé de la connexion humaine.",
    "Croyez en votre propre capacité à créer la vie que vous désirez ; vous avez le pouvoir de le réaliser.",
    "Soyez ouvert à la possibilité de miracles ; ils peuvent survenir lorsque vous y moins vous attendez.",
    "Apprenez à lâcher prise de ce qui ne vous sert plus ; cela vous permettra de vous ouvrir à de nouvelles possibilités.",
    "Soyez patient avec les autres ; tout le monde est en train de grandir et d'apprendre à son propre rythme.",
    "Ne laissez pas la peur vous empêcher de poursuivre vos rêves ; osez vous aventurer dans l'inconnu.",
    "Exprimez votre gratitude quotidiennement ; cela ouvrira votre cœur à plus d'amour et de compassion.",
    "Soyez présent dans chaque moment ; c'est là que réside la plénitude et la joie de vivre.",
    "Croyez en votre propre capacité à surmonter les défis ; vous êtes plus fort que vous ne le pensez.",
    "Ne sous-estimez jamais le pouvoir de la gentillesse ; elle peut guérir les cœurs et changer des vies.",
    "Apprenez à lâcher prise de ce qui ne vous sert plus ; cela vous ouvrira la voie à de nouveaux départs.",
    "Soyez reconnaissant pour chaque expérience de vie ; elles ont toutes quelque chose à vous enseigner.",
    "Chaque défi est une occasion de croissance ; ne le craignez pas, mais embrassez-le.",
    "Soyez doux avec vous-même ; vous êtes en train de grandir et d'apprendre.",
    "Trouvez la joie dans les petites victoires de la vie ; elles sont toutes précieuses.",
    "Soyez ouvert à l'inconnu ; c'est là que se trouvent les plus grandes opportunités.",
    "Croyez en votre pouvoir de créer la vie que vous désirez ; vous êtes plus puissant que vous ne le pensez.",
    "Faites confiance au processus de la vie ; tout se déroule exactement comme il le devrait.",
    "Appréciez le voyage autant que la destination ; chaque étape a sa propre beauté.",
    "Soyez un exemple de bonté et de compassion ; le monde a besoin de plus de lumière.",
    "Croyez en vous-même, même lorsque personne d'autre ne le fait ; vous êtes votre propre meilleur allié.",
    "Soyez patient avec les autres ; tout le monde est en train de grandir à son propre rythme.",
    "Ne laissez pas la peur vous empêcher d'essayer ; c'est là que se trouvent les plus grandes réalisations.",
    "Soyez reconnaissant pour chaque expérience de vie ; elles ont toutes quelque chose à vous enseigner.",
    "Chaque jour est une nouvelle chance de devenir la meilleure version de vous-même ; saisissez-la avec gratitude.",
    "Faites preuve de gratitude pour les leçons apprises et les défis surmontés ; ils vous rendent plus fort.",
    "Ne laissez pas la peur vous retenir ; avancez avec courage et détermination.",
    "Cultivez un esprit de gratitude ; cela vous apportera plus de bonheur et de paix intérieure.",
    "Soyez ouvert à l'impermanence de la vie ; c'est là que réside sa beauté et sa magie.",
    "Faites confiance à votre voyage ; même les détours ont leur propre signification.",
    "Ne laissez pas la peur vous empêcher de suivre vos rêves ; osez vous aventurer dans l'inconnu.",
    "Apprenez à lâcher prise de ce qui ne vous sert plus ; cela vous ouvrira la voie à de nouvelles possibilités.",
    "Soyez ouvert à la possibilité de changement ; c'est là que réside la croissance personnelle.",
    "Soyez gentil avec vous-même ; vous faites de votre mieux et c'est tout ce qui compte.",
    "Chaque jour est une nouvelle opportunité de grandir et d'apprendre ; saisissez-la avec gratitude.",
    "Faites preuve de compassion envers vous-même ; vous méritez d'être aimé et apprécié.",
    "Ne vous attardez pas sur le passé ; concentrez-vous sur le présent et sur ce qui est à venir.",
    "Soyez reconnaissant pour les petites choses de la vie ; elles sont souvent les plus importantes.",
    "Ne laissez pas la peur vous retenir ; osez sortir de votre zone de confort et explorer de nouvelles possibilités.",
    "Soyez ouvert à la possibilité de miracles ; ils se produisent souvent lorsque vous y moins vous attendez.",
    "Faites preuve de patience dans toutes les choses ; chaque chose vient en son temps.",
    "Croyez en votre pouvoir de changer votre vie ; vous êtes le seul à pouvoir réaliser vos rêves.",
    "Soyez reconnaissant pour les leçons que la vie vous offre ; elles vous aident à grandir et à évoluer.",
    "Chaque défi est une opportunité de croissance ; ne le craignez pas, mais embrassez-le.",
    "Apprenez à écouter votre intuition ; elle est souvent plus sage que votre esprit.",
    "Soyez ouvert aux possibilités infinies de l'univers ; elles sont plus grandes que vous ne pouvez l'imaginer.",
    "Soyez reconnaissant pour chaque nouvelle journée ; c'est une chance de recommencer.",
    "N'ayez pas peur de l'échec ; c'est une occasion d'apprendre et de grandir.",
    "Faites preuve de gentillesse envers vous-même et envers les autres ; elle est la clé de la connexion humaine.",
    "Croyez en votre propre capacité à créer la vie que vous désirez ; vous avez le pouvoir de le réaliser.",
    "Soyez ouvert à la possibilité de miracles ; ils peuvent survenir lorsque vous y moins vous attendez.",
    "Apprenez à lâcher prise de ce qui ne vous sert plus ; cela vous permettra de vous ouvrir à de nouvelles possibilités.",
    "Soyez patient avec les autres ; tout le monde est en train de grandir et d'apprendre à son propre rythme.",
    "Ne laissez pas la peur vous empêcher de poursuivre vos rêves ; osez vous aventurer dans l'inconnu.",
    "Exprimez votre gratitude quotidiennement ; cela ouvrira votre cœur à plus d'amour et de compassion.",
    "Soyez présent dans chaque moment ; c'est là que réside la plénitude et la joie de vivre.",
    "Croyez en votre propre capacité à surmonter les défis ; vous êtes plus fort que vous ne le pensez.",
    "Ne sous-estimez jamais le pouvoir de la gentillesse ; elle peut guérir les cœurs et changer des vies.",
    "Apprenez à lâcher prise de ce qui ne vous sert plus ; cela vous ouvrira la voie à de nouveaux départs.",
    "Soyez reconnaissant pour chaque expérience de vie ; elles ont toutes quelque chose à vous enseigner.",
    "Chaque défi est une occasion de croissance ; ne le craignez pas, mais embrassez-le.",
    "Soyez doux avec vous-même ; vous êtes en train de grandir et d'apprendre.",
    "Trouvez la joie dans les petites victoires de la vie ; elles sont toutes précieuses.",
    "Soyez ouvert à l'inconnu ; c'est là que se trouvent les plus grandes opportunités.",
    "Croyez en votre pouvoir de créer la vie que vous désirez ; vous êtes plus puissant que vous ne le pensez.",
    "Faites confiance au processus de la vie ; tout se déroule exactement comme il le devrait.",
    "Appréciez le voyage autant que la destination ; chaque étape a sa propre beauté.",
    "Soyez un exemple de bonté et de compassion ; le monde a besoin de plus de lumière.",
    "Croyez en vous-même, même lorsque personne d'autre ne le fait ; vous êtes votre propre meilleur allié.",
    "Soyez patient avec les autres ; tout le monde est en train de grandir à son propre rythme.",
    "Ne laissez pas la peur vous empêcher d'essayer ; c'est là que se trouvent les plus grandes réalisations.",
    "Soyez reconnaissant pour chaque expérience de vie ; elles ont toutes quelque chose à vous enseigner.",
    "Chaque jour est une nouvelle chance de devenir la meilleure version de vous-même ; saisissez-la avec gratitude.",
    "Faites preuve de gratitude pour les leçons apprises et les défis surmontés ; ils vous rendent plus fort.",
    "Ne laissez pas la peur vous retenir ; avancez avec courage et détermination.",
    "Cultivez un esprit de gratitude ; cela vous apportera plus de bonheur et de paix intérieure.",
    "Soyez ouvert à l'impermanence de la vie ; c'est là que réside sa beauté et sa magie.",
    "Faites confiance à votre voyage ; même les détours ont leur propre signification.",
    "Ne laissez pas la peur vous empêcher de suivre vos rêves ; osez vous aventurer dans l'inconnu.",
    "Apprenez à lâcher prise de ce qui ne vous sert plus ; cela vous ouvrira la voie à de nouvelles possibilités.",
    "Soyez ouvert à la possibilité de changement ; c'est là que réside la croissance personnelle.",
    "Soyez gentil avec vous-même ; vous faites de votre mieux et c'est tout ce qui compte.",
    "Chaque jour est une nouvelle opportunité de grandir et d'apprendre ; saisissez-la avec gratitude.",
    "Faites preuve de compassion envers vous-même ; vous méritez d'être aimé et apprécié.",
    "Ne vous attardez pas sur le passé ; concentrez-vous sur le présent et sur ce qui est à venir.",
    "Soyez reconnaissant pour les petites choses de la vie ; elles sont souvent les plus importantes.",
    "Ne laissez pas la peur vous retenir ; osez sortir de votre zone de confort et explorer de nouvelles possibilités.",
    "Soyez ouvert à la possibilité de miracles ; ils se produisent souvent lorsque vous y moins vous attendez.",
    "Faites preuve de patience dans toutes les choses ; chaque chose vient en son temps.",
    "Croyez en votre pouvoir de changer votre vie ; vous êtes le seul à pouvoir réaliser vos rêves.",
    "Soyez reconnaissant pour les leçons que la vie vous offre ; elles vous aident à grandir et à évoluer.",
    "Chaque défi est une opportunité de croissance ; ne le craignez pas, mais embrassez-le.",
    "Apprenez à écouter votre intuition ; elle est souvent plus sage que votre esprit.",
    "Soyez ouvert aux possibilités infinies de l'univers ; elles sont plus grandes que vous ne pouvez l'imaginer.",
    "Soyez reconnaissant pour chaque nouvelle journée ; c'est une chance de recommencer.",
    "N'ayez pas peur de l'échec ; c'est une occasion d'apprendre et de grandir.",
    "Faites preuve de gentillesse envers vous-même et envers les autres ; elle est la clé de la connexion humaine.",
    "Croyez en votre propre capacité à créer la vie que vous désirez ; vous avez le pouvoir de le réaliser.",
    "Soyez ouvert à la possibilité de miracles ; ils peuvent survenir lorsque vous y moins vous attendez.",
    "Apprenez à lâcher prise de ce qui ne vous sert plus ; cela vous permettra de vous ouvrir à de nouvelles possibilités.",
    "Soyez patient avec les autres ; tout le monde est en train de grandir et d'apprendre à son propre rythme.",
    "Ne laissez pas la peur vous empêcher de poursuivre vos rêves ; osez vous aventurer dans l'inconnu.",
    "Exprimez votre gratitude quotidiennement ; cela ouvrira votre cœur à plus d'amour et de compassion.",
    "Soyez présent dans chaque moment ; c'est là que réside la plénitude et la joie de vivre.",
    "Croyez en votre propre capacité à surmonter les défis ; vous êtes plus fort que vous ne le pensez.",
    "Ne sous-estimez jamais le pouvoir de la gentillesse ; elle peut guérir les cœurs et changer des vies.",
    "Apprenez à lâcher prise de ce qui ne vous sert plus ; cela vous ouvrira la voie à de nouveaux départs.",
    "Soyez reconnaissant pour chaque expérience de vie ; elles ont toutes quelque chose à vous enseigner.",
    "Chaque défi est une occasion de croissance ; ne le craignez pas, mais embrassez-le.",
    "Soyez doux avec vous-même ; vous êtes en train de grandir et d'apprendre.",
    "Trouvez la joie dans les petites victoires de la vie ; elles sont toutes précieuses.",
    "Soyez ouvert à l'inconnu ; c'est là que se trouvent les plus grandes opportunités.",
    "Croyez en votre pouvoir de créer la vie que vous désirez ; vous êtes plus puissant que vous ne le pensez.",
    "Faites confiance au processus de la vie ; tout se déroule exactement comme il le devrait.",
    "Appréciez le voyage autant que la destination ; chaque étape a sa propre beauté.",
    "Soyez un exemple de bonté et de compassion ; le monde a besoin de plus de lumière.",
    "Croyez en vous-même, même lorsque personne d'autre ne le fait ; vous êtes votre propre meilleur allié.",
    "Soyez patient avec les autres ; tout le monde est en train de grandir à son propre rythme.",
    "Ne laissez pas la peur vous empêcher d'essayer ; c'est là que se trouvent les plus grandes réalisations.",
    "Soyez reconnaissant pour chaque expérience de vie ; elles ont toutes quelque chose à vous enseigner.",
    "Chaque jour est une nouvelle chance de devenir la meilleure version de vous-même ; saisissez-la avec gratitude.",
    "Faites preuve de gratitude pour les leçons apprises et les défis surmontés ; ils vous rendent plus fort.",
    "Ne laissez pas la peur vous retenir ; avancez avec courage et détermination.",
    "Cultivez un esprit de gratitude ; cela vous apportera plus de bonheur et de paix intérieure.",
    "Soyez ouvert à l'impermanence de la vie ; c'est là que réside sa beauté et sa magie.",
    "Faites confiance à votre voyage ; même les détours ont leur propre signification.",
    "Ne laissez pas la peur vous empêcher de suivre vos rêves ; osez vous aventurer dans l'inconnu.",
    "Apprenez à lâcher prise de ce qui ne vous sert plus ; cela vous ouvrira la voie à de nouvelles possibilités.",
    "Soyez ouvert à la possibilité de changement ; c'est là que réside la croissance personnelle.",
    "Soyez gentil avec vous-même ; vous faites de votre mieux et c'est tout ce qui compte.",
    "Chaque jour est une nouvelle opportunité de grandir et d'apprendre ; saisissez-la avec gratitude.",
    "Faites preuve de compassion envers vous-même ; vous méritez d'être aimé et apprécié.",
    "Ne vous attardez pas sur le passé ; concentrez-vous sur le présent et sur ce qui est à venir.",
    "Soyez reconnaissant pour les petites choses de la vie ; elles sont souvent les plus importantes.",
    "Ne laissez pas la peur vous retenir ; osez sortir de votre zone de confort et explorer de nouvelles possibilités."
]

module.exports = french