const english = [
    "Destiny favors the bold. Fear not to move forward.",
    "Believe in yourself, for you are stronger than you think.",
    "True love never fails; allow yourself to love and be loved.",
    "Be patient; everything happens in its own time.",
    "Every challenge brings with it an opportunity for growth.",
    "Trust your intuition; it is your inner compass.",
    "Follow your heart, but take your mind with you.",
    "Maintain balance between work, rest, and play.",
    "Value the little things; they hold great meaning.",
    "Gratitude is the key to a fulfilling life; be thankful for what you have.",
    "Take care of your body, mind, and spirit; they are your greatest treasures.",
    "Do not worry about what others think of you; be authentic.",
    "Life is a journey; enjoy the path, not just the destination.",
    "Forgive those who have hurt you; forgiveness brings liberation.",
    "Be kind to others; you never know what battles they are facing.",
    "Adversity is just a test; you are stronger than you imagine.",
    "Open yourself to new experiences; they can bring wonderful surprises.",
    "Do not dwell on the past; the present is where the magic happens.",
    "Life is made of ups and downs; embrace all your emotions.",
    "Learn from your mistakes; they are opportunities for growth.",
    "Do not compare your journey to others'; everyone has their own path.",
    "Be patient with yourself; progress takes time.",
    "True beauty comes from within; cultivate your essence.",
    "Simplicity is the key to happiness; value what truly matters.",
    "Stay true to your values; they are your moral compass.",
    "Do not fear change; it is inevitable and necessary for growth.",
    "Accept challenges as opportunities for learning.",
    "Find joy in the simple things in life; they are the most precious.",
    "Be as flexible as bamboo; bend, but never break.",
    "Authenticity is your greatest strength; be true to yourself.",
    "Do not worry about what you cannot control; focus on what you can.",
    "Believe in the power of your dreams; they have the potential to come true.",
    "Express your gratitude daily; it attracts more reasons to be grateful.",
    "Learn to let go of what no longer serves you; it will make room for the new.",
    "Be patient with others; everyone is on their own journey of growth.",
    "Life is a precious gift; live each moment with gratitude and joy.",
    "Appreciate the beauty around you; it is present in the simplest of details.",
    "Never underestimate the power of kindness; it can transform lives.",
    "Embrace uncertainty; it is where the magic of life resides.",
    "Do not worry about the future; focus on the present and do your best now.",
    "Be a beacon of light for others; your shine can illuminate the path.",
    "Value your relationships; they make the journey of life meaningful.",
    "Learn to listen to your inner voice; it always knows what's best for you.",
    "Do not be afraid to fail; it is through failures that you learn and grow.",
    "Keep an open mind; knowledge and wisdom are constantly evolving.",
    "Do not compare yourself to others; you are unique and have your own path to follow.",
    "Practice self-compassion; be kind to yourself in times of difficulty.",
    "Follow your dreams with courage and determination; the universe is rooting for you.",
    "Find joy in moments of stillness; it is there that you find clarity and peace.",
    "Do not be swayed by fear; it is merely an illusion that limits your potential.",
    "Be grateful for the lessons life offers you; they are opportunities for growth.",
    "Find joy in the journey, not just the destination.",
    "Life is a dance; follow the rhythm of the universe and let yourself be carried by the music of existence.",
    "Cultivate patience; great things take time to manifest.",
    "Be present in each moment; that's where the magic of life happens.",
    "Trust in the power of the universe; it will always guide you in the right direction.",
    "Do not fear the darkness; it is where you discover your own light.",
    "Be kind to yourself; you are your best friend and ally.",
    "Life is a precious gift; live it with gratitude and joy.",
    "Follow the signs of the universe; they are clues to your destiny.",
    "Do not worry about what others think of you; follow your own path with confidence.",
    "Accept what you cannot change; focus on what is within your reach.",
    "Find beauty in imperfection; it is what makes life interesting and unique.",
    "Keep the faith, even in the darkest moments; light will always prevail.",
    "Share your love and kindness with the world; that's what makes a difference.",
    "Do not forget to take care of yourself; your health and well-being are priorities.",
    "Learn to say yes to new opportunities; they can lead you to unexpected places.",
    "Be grateful for the people in your life; they are precious gifts.",
    "Do not worry about what could go wrong; focus on what could go right.",
    "Trust in your journey; each challenge is an opportunity for growth.",
    "Be brave in your choices; that's how you discover what is possible.",
    "Do not forget to celebrate your victories; they are a testament to your power.",
    "Learn to let go of what no longer serves you; that's where your freedom lies.",
    "Value the journey as much as the destination; that's where you find your true essence.",
    "Learn to love yourself unconditionally; that's where your power lies.",
    "Do not worry about what you cannot control; focus on what you can do.",
    "Find joy in the simple things in life; they are what makes life truly beautiful.",
    "Be kind to others, even when you disagree; that's where true greatness lies.",
    "Trust your intuition; it's your inner compass, guiding you in the right direction.",
    "Learn to live with gratitude; that's where the true wealth of life lies.",
    "Be patient with others; everyone is fighting their own battles.",
    "Do not worry about the future; focus on the present and what's within your reach.",
    "Believe in the power of your dreams; they have the power to shape your destiny.",
    "Be kind to yourself; you are your best friend and ally on this journey of life.",
    "Do not forget to laugh and have fun; that's where the true magic of life lies."
]

module.exports = english